# -*- mode: ruby -*-
# vi: set ft=ruby :

# If the berkshelf plugin isn't installed, do so using:
# > vagrant plugin install vagrant-berkshelf
require 'berkshelf/vagrant'

Vagrant.configure("2") do |config|
  config.vm.box = "opscode-ubuntu-12.04-i386"
  config.vm.box_url = "https://opscode-vm.s3.amazonaws.com/vagrant/opscode_ubuntu-12.04-i386_provisionerless.box"

  # Port forwarding for the Neo4j web interface:
  config.vm.network :forwarded_port, guest: 7474, host: 7474

  # Make sure Chef is installed with the latest version:
  config.omnibus.chef_version = :latest

  # Set the path the the Berksfile
  config.berkshelf.berksfile_path = "../../Berksfile"

  # Tell vagrant to turn on the berkshelf plugin:
  config.berkshelf.enabled = true

  # Provision the VM:
  config.vm.provision :chef_solo do |chef|
    # Not needed now that berkshelf has taken over:
    # chef.cookbooks_path = "../../cookbooks/"
    chef.add_recipe "apt"
    chef.add_recipe "neo4j-server::tarball"
  end
end
